services:
    postgres:
        image: postgres:latest
        restart: always
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'pg_isready -U ${POSTGRES_USER}',
                ]
            interval: 10s
            timeout: 5s
            retries: 5
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '5432:5432'
        volumes:
            - pg_data:/var/lib/postgresql/data
        networks:
            - backend

volumes:
    pg_data:

networks:
    backend:
